import Chat from '@styled-icons/bootstrap/ChatSquare'
import Crown from '@styled-icons/remix-line/VipCrown'
import Bell from '@styled-icons/bootstrap/Bell'
import Heart from '@styled-icons/bootstrap/SuitHeart'
import ArrowLeft from '@styled-icons/evaicons-outline/ArrowIosBackOutline'
import ArrowRight from'@styled-icons/evaicons-outline/ArrowIosForwardOutline'
import ArrowClose from'@styled-icons/boxicons-regular/ArrowFromRight'
import MoreHorizontal from'@styled-icons/evaicons-outline/MoreHorizontalOutline'
import Search from'@styled-icons/entypo/MagnifyingGlass'
import Backup from'@styled-icons/material-outlined/SettingsBackupRestore'
import Delete from'@styled-icons/typicons/DeleteOutline'
import Twitchs from'@styled-icons/fa-brands/Twitch'
import {Twitch} from 'styled-icons/fa-brands'